name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  # =======================
  # 1. LINT
  # =======================
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile -w

      - name: Run Eslint and Stylelint
        run: pnpm lint

  # =======================
  # 2. FORMAT
  # =======================
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile -w

      - name: Check format
        run: pnpm format

  # =======================
  # 3. CHECK TYPES
  # =======================
  check-types:
    name: Check Types
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile -w

      - name: Install web dependencies
        run: pnpm --filter=web install

      - name: Check types
        run: pnpm --filter=web check-types

  # =======================
  # 4. BUILD
  # =======================
  build:
    name: Build Web
    runs-on: ubuntu-latest
    needs: [lint, format, check-types]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile -w

      - name: Install web dependencies
        run: pnpm --filter=web install

      - name: Build web app
        run: pnpm web:build
